# Generated by Django 6.1.1 on 2026-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва продукту')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('weight_grams', models.PositiveIntegerField(verbose_name='Вага (г)')),
                ('expiry_date', models.DateField(verbose_name='Термін придатності')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
            ],
        ),
    ]
